### ISSUE TITLE
Doubts about shared weights for backbone networks

### ISSUE THREAD

**Issue by Geleven7** [XueZ-phd/TFDet#3]
As described in the article, the benefit of shared weights is that it reduces the computation and parameters. In addition, I think that using a backbone network with shared weights for feature extraction on RGBT images, the feature maps on each channel are just going to be more similar, and so the conclusion is obtained that the feature similarity is greater for the diagonal channel. But does this conclusion still hold for networks where weights are not shared?

**Comment by XueZ-phd** [comment]
Correct. The new finding of parallel-channel similarity is based on the use of a backbone network with shared weights.

Because we believe that the backbone network with shared weights has the advantages of preventing overfitting and reducing the number of parameters, we focus on adopting this structure. 

We did not test whether this phenomenon exists in networks that do not share weights, as it was not the focus of this work. If we have time later, we will investigate whether this phenomenon is also present in backbone networks without shared weights.

Thank you for your question.

**Comment by Geleven7** [comment]
Thank you for your answers, your work is so excellent and rigorous, good luck with your research!

**Comment by XueZ-phd** [comment]
Thank you.
